schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0-rc.1"
    hash = "sha256-3DboBqby2ejRU33FG96Z8JF5AJ8HP2rC/v++VyoQ2LQ="
  [mod."github.com/AndreasBriese/bbloom"]
    version = "v0.0.0-20190825152654-46b345b51c96"
    hash = "sha256-ydIJ4QKvQsDSAook9y0doDaTeXpyQUy1T+ySfOgFLAg="
  [mod."github.com/BurntSushi/toml"]
    version = "v1.2.0"
    hash = "sha256-yxBUbKQ3v4Na9IHDf4PLePrILAX4kmk2Zc+kqWazlIY="
  [mod."github.com/Masterminds/goutils"]
    version = "v1.1.1"
    hash = "sha256-MEvA5e099GUllILa5EXxa6toQexU1sz6eDZt2tiqpCY="
  [mod."github.com/Masterminds/semver/v3"]
    version = "v3.1.1"
    hash = "sha256-6AbVa1URv04zlxUZA/Wc484EzrzgAuPcuub3WFBRWDc="
  [mod."github.com/Masterminds/sprig/v3"]
    version = "v3.2.2"
    hash = "sha256-XXDG2ImEqg+TbrXBNYAXaqeV0H/nsNRfijqctCv8y3E="
  [mod."github.com/alecthomas/chroma"]
    version = "v0.10.0"
    hash = "sha256-p721vddVTv4iv1O0/dqpdk5xF6x9iLIHcrfh8JEVnqQ="
  [mod."github.com/antlr/antlr4/runtime/Go/antlr"]
    version = "v1.4.10"
    hash = "sha256-QZn1eltqxkZYvf7g/GQv6HftH+OuKJTVjIjyyHZw9jI="
  [mod."github.com/aryann/difflib"]
    version = "v0.0.0-20210328193216-ff5ff6dc229b"
    hash = "sha256-QaGcdek1bA6eekbxVTDaidFZrWeGk+of35NTV94lVXw="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20210307081110-f21760c49a8d"
    hash = "sha256-5ZVRCOiNcvpmK3/mhtF1Iy0naPFVVhmXXQmC6eaJExk="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/caddy-dns/namecheap"]
    version = "v0.0.0-20211109044219-3e5991606a7a"
    hash = "sha256-MtKcYiU0m0I1O8cncwF8GbhueuQwEPhbsTabe+BBZJA="
  [mod."github.com/caddy-dns/netlify"]
    version = "v1.0.1"
    hash = "sha256-VVDza1ChdBTmZLdGLlKuEfk3kEEAefK0A6fcDDNi2AI="
  [mod."github.com/caddyserver/caddy/v2"]
    version = "v2.6.2"
    hash = "sha256-wTKacUCtDMEaCmAGEGNBrLUI6xX2clUjLVzBUof0XQE="
  [mod."github.com/caddyserver/certmagic"]
    version = "v0.17.2"
    hash = "sha256-FPvR3VeoI+VdMkrkT+TUSgpnlMm85gUqlFfq8/HMo9c="
  [mod."github.com/cenkalti/backoff/v4"]
    version = "v4.1.2"
    hash = "sha256-35Dk9c8Om+NSVKGwu8MwJkB8ig8mDLRviCIYbIRAgiE="
  [mod."github.com/cespare/xxhash"]
    version = "v1.1.0"
    hash = "sha256-nVDTtXH9PC3yJ0THaQZEN243UP9xgLi/clt5xRqj3+M="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chzyer/readline"]
    version = "v0.0.0-20180603132655-2972be24d48e"
    hash = "sha256-2Uj5LGpHEbLQG3d/7z9AL8DknUBZyoTAMs4j+VVDmIA="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/dgraph-io/badger"]
    version = "v1.6.2"
    hash = "sha256-D/iXyiNZ8/7tBtA9msk10vVWfohWEPqFdobzRwKlvQQ="
  [mod."github.com/dgraph-io/badger/v2"]
    version = "v2.2007.4"
    hash = "sha256-+KwqZJZpViv8S3TqUVvPXrFoMgWFyS3NoLsi4RR5fGk="
  [mod."github.com/dgraph-io/ristretto"]
    version = "v0.0.4-0.20200906165740-41ebdbffecfd"
    hash = "sha256-rytPqFZwSv+JtQEtF0GrmOlD+eY8lF1v7M54NcFi3Go="
  [mod."github.com/dgryski/go-farm"]
    version = "v0.0.0-20200201041132-a6ae2369ad13"
    hash = "sha256-aOMlPwFY36bLiiIx4HonbCYRAhagk5N6HAWN7Ygif+E="
  [mod."github.com/dlclark/regexp2"]
    version = "v1.4.0"
    hash = "sha256-Pk/S2x2rX7xnGFLyoHEw09CoNQimvz/msdPRsxLaLsc="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1-0.20200219035652-afde56e7acac"
    hash = "sha256-EojJ9pqW5PpA0viodpi28RCz2tXUBqfYBA0AMYL9nSc="
  [mod."github.com/felixge/httpsnoop"]
    version = "v1.0.3"
    hash = "sha256-qV3UPYKKBQDTzAUzzsTpfdbGhFnkmTO/r5ylPL1SyfA="
  [mod."github.com/fsnotify/fsnotify"]
    version = "v1.5.1"
    hash = "sha256-B8kZ8yiWgallT7R2j1kSRJcJkSGFVf9ise+TpXa+7XY="
  [mod."github.com/go-chi/chi"]
    version = "v4.1.2+incompatible"
    hash = "sha256-KpvSwEqRBeUBZae9r7J3sMCpJMqyaKtEn1KKfKTa0O0="
  [mod."github.com/go-kit/kit"]
    version = "v0.10.0"
    hash = "sha256-fkr/mndYfh5dSepwRggu3ZIpwAomvwrg4LQ/foBpAd4="
  [mod."github.com/go-logfmt/logfmt"]
    version = "v0.5.1"
    hash = "sha256-t50m9ffvW8PiGvO+2svnLI+N/XaWaBS+ZlhwrEQn2gU="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.3"
    hash = "sha256-2L7k6GfrcW3GXXYr1FYIu20aZBjIF0cTKdte6D4riH8="
  [mod."github.com/go-logr/stdr"]
    version = "v1.2.2"
    hash = "sha256-rRweAP7XIb4egtT1f2gkz4sYOu7LDHmcJ5iNsJUd0sE="
  [mod."github.com/go-openapi/analysis"]
    version = "v0.21.4"
    hash = "sha256-W+tDQJ6mwhUoKQO5AB6xHCu8n5K9DsSz7Z89Wol5zxA="
  [mod."github.com/go-openapi/errors"]
    version = "v0.20.3"
    hash = "sha256-unuZ9+J0o606DRdTFOvZFaeMY7JcsD/RG+9W3w87zlE="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/loads"]
    version = "v0.21.2"
    hash = "sha256-rAomEEL0rgthNa6XlN0tjTMUjXqkNmyFFpQmIoh4hmU="
  [mod."github.com/go-openapi/runtime"]
    version = "v0.19.24"
    hash = "sha256-bMNx+ogfhLB+F2mGAC6vlMt8uNBa6C1yGMcJjjDlgjc="
  [mod."github.com/go-openapi/spec"]
    version = "v0.20.8"
    hash = "sha256-1hj2wZBodG0yw86vEKL9+u1LGwHRXrhRVDzvGpM8o9M="
  [mod."github.com/go-openapi/strfmt"]
    version = "v0.21.3"
    hash = "sha256-tg2JEoiNcMIyRHntVIW0UMuKchfl4jYZoHchOsVRVj4="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/go-openapi/validate"]
    version = "v0.20.0"
    hash = "sha256-5ydNvS0284/ZVFsipaOmnRgliphiOmV2ROWJPDp+t50="
  [mod."github.com/go-sql-driver/mysql"]
    version = "v1.6.0"
    hash = "sha256-mMIiUN5XUXxYOpdlMQMFzYB4AX2xrpGgkkEBL0jLKrg="
  [mod."github.com/go-task/slim-sprig"]
    version = "v0.0.0-20210107165309-348f09dbbbc0"
    hash = "sha256-jgza4peLzeJlwmMh/c1gNkmtwA9YtSdGaBzBUDXhIZo="
  [mod."github.com/golang/mock"]
    version = "v1.6.0"
    hash = "sha256-fWdnMQisRbiRzGT3ISrUHovquzLRHWvcv1JEsJFZRno="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/golang/snappy"]
    version = "v0.0.4"
    hash = "sha256-Umx+5xHAQCN/Gi4HbtMhnDCSPFAXSsjVbXd8n5LhjAA="
  [mod."github.com/google/cel-go"]
    version = "v0.12.5"
    hash = "sha256-s9PcuNDhWn+m7f9r2tepTeMZb9Mtou21rD4fOKX2hp8="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/grpc-ecosystem/grpc-gateway"]
    version = "v1.16.0"
    hash = "sha256-wLymGic7wZ6fSiBYDAaGqnQ9Ste1fUWeqXeolZXCHvI="
  [mod."github.com/huandu/xstrings"]
    version = "v1.3.2"
    hash = "sha256-ueAZrYRXMdRpeTKct3Yxa5YXkCZEoUHpNQs7wLLJil8="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.12"
    hash = "sha256-IPGunEznxlUilS22LUU4p/QTA7f5+Goowf1Utg9ARpc="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.0.0"
    hash = "sha256-ogTuLrV40FwS4ueo4hh6hi1wPywOI+LyIqfNjsibwNY="
  [mod."github.com/jackc/chunkreader/v2"]
    version = "v2.0.1"
    hash = "sha256-LNAEmbsxWOVPtcQ1fE1JC1yTaqyvZGa/k4zocWFBRTo="
  [mod."github.com/jackc/pgconn"]
    version = "v1.10.1"
    hash = "sha256-eeTbrnllrbpYBQA0YvEq1OEv1dFWvN7yaZdDqNPOmQ8="
  [mod."github.com/jackc/pgio"]
    version = "v1.0.0"
    hash = "sha256-4W0PGZlkbBZcSJmPyXi9v1gAJIK9ujVLlcbxEOx9J1A="
  [mod."github.com/jackc/pgpassfile"]
    version = "v1.0.0"
    hash = "sha256-H0nFbC34/3pZUFnuiQk9W7yvAMh6qJDrqvHp+akBPLM="
  [mod."github.com/jackc/pgproto3/v2"]
    version = "v2.2.0"
    hash = "sha256-f7MKCvqPFa+xcAsUOiIs9mQUWOyHeUu7EqXvdU2apOI="
  [mod."github.com/jackc/pgservicefile"]
    version = "v0.0.0-20200714003250-2b9c44734f2b"
    hash = "sha256-sNfMMlmdlb5P4a4EgIHaHOcHD9N6IflYHjWj0hSI640="
  [mod."github.com/jackc/pgtype"]
    version = "v1.9.0"
    hash = "sha256-Yn5CHleshysFaXb56uMek24ZUgBSRRLM12710zQbhcA="
  [mod."github.com/jackc/pgx/v4"]
    version = "v4.14.0"
    hash = "sha256-3rz4AI9bv51YUSo4VWSTxoZw8bAXwM6vONv9TC/lMoA="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/klauspost/compress"]
    version = "v1.15.11"
    hash = "sha256-9MXm0TObg6DyqnYMIw3IChrorHc2ILf5djZYoM0e1J0="
  [mod."github.com/klauspost/cpuid/v2"]
    version = "v2.1.1"
    hash = "sha256-Ru6KSK9N08IxuwinJA1c+1zA04rTY8kcHBcKThMqZkE="
  [mod."github.com/libdns/libdns"]
    version = "v0.2.1"
    hash = "sha256-bxEY0wYu4Um0t7sakLyMwMPDXfv2x07gjckKSyAypsc="
  [mod."github.com/libdns/namecheap"]
    version = "v0.0.0-20211109042440-fc7440785c8e"
    hash = "sha256-fwfCHhHsLDnktt5nqaGUJi/TwZ/sOmzXd9DmPnX2M+8="
  [mod."github.com/libdns/netlify"]
    version = "v1.0.2"
    hash = "sha256-6ZCmiv/jbkSS3uB6B/6W1YX+YOYuZ86t+bZ7bz1E9hY="
  [mod."github.com/lucas-clemente/quic-go"]
    version = "v0.29.2"
    hash = "sha256-jR8d+Zzd0lQd/jtTx9CHkU30jy+v1rjF9Xqnr8eAUlw="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/manifoldco/promptui"]
    version = "v0.9.0"
    hash = "sha256-Fe2OPoyRExZejwtUBivKhfJAJW7o9b1eyYpgDlWQ1No="
  [mod."github.com/marten-seemann/qpack"]
    version = "v0.2.1"
    hash = "sha256-FMWYbeOBc0TKdUe9B2XI1N2q1e7/Vta5VhOMpra9TuQ="
  [mod."github.com/marten-seemann/qtls-go1-18"]
    version = "v0.1.3"
    hash = "sha256-tj+99TXQHJlcK6NB8t8XTeUWsT33X1DGP53YGh3QKBU="
  [mod."github.com/marten-seemann/qtls-go1-19"]
    version = "v0.1.1"
    hash = "sha256-WjRyc/T0abZpJIaC2BqPBj8QcFJcFSTvQRtm1wQt8yE="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.8"
    hash = "sha256-TBXc2n5tRebabjt0HipS8wCdRml0kM0JjpppUbdx1XQ="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.13"
    hash = "sha256-8dof20YZW6ado90UG9kDrjCAnlWyRSOE3Jw4K3WEZyQ="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/mholt/acmez"]
    version = "v1.0.4"
    hash = "sha256-HXGdY4WtS5V70hWRScTzQdc/3OY5gp5aRzCfIfWIqVo="
  [mod."github.com/mholt/caddy-dynamicdns"]
    version = "v0.0.0-20220916142711-87eacc5e2482"
    hash = "sha256-7ZCaZzJWLsVZ/W1mU8rKsOP5WHI1GEtgvGk4c1k+pjA="
  [mod."github.com/micromdm/scep/v2"]
    version = "v2.1.0"
    hash = "sha256-vs0CBvUVXRh6n+XI7GlvdijNC9/Vec0LpywCCEivo0g="
  [mod."github.com/miekg/dns"]
    version = "v1.1.50"
    hash = "sha256-mtf3QAk46pCA0a1K+oH6a7oqsY6LR6Qr8HD4qnDqe+s="
  [mod."github.com/mitchellh/copystructure"]
    version = "v1.2.0"
    hash = "sha256-VR9cPZvyW62IHXgmMw8ee+hBDThzd2vftgPksQYR/Mc="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/mitchellh/mapstructure"]
    version = "v1.5.0"
    hash = "sha256-ztVhGQXs67MF8UadVvG72G3ly0ypQW0IRDdOOkjYwoE="
  [mod."github.com/mitchellh/reflectwalk"]
    version = "v1.0.2"
    hash = "sha256-VX9DPqChm7jPnyrA3RAYgxAFrAhj7TRKIWD/qR9Zr9s="
  [mod."github.com/netlify/open-api/v2"]
    version = "v2.12.2"
    hash = "sha256-BXXtZt5ZseEilCaXPiL0SpOyJ8YZeTV5Meu/43wfCsY="
  [mod."github.com/nxadm/tail"]
    version = "v1.4.8"
    hash = "sha256-JP3RZVZLFhaBZ2VdF/fbyMPMLqrPZDjP98f1ey2OePo="
  [mod."github.com/oklog/ulid"]
    version = "v1.3.1"
    hash = "sha256-LNn883rYNiaoY9sGEPIzlMRx5UwGThdYTjXqfzeGc9k="
  [mod."github.com/onsi/ginkgo"]
    version = "v1.16.4"
    hash = "sha256-+rsbCrlS+05k+G14Ov/GYAmpLN09Vp0F2LMKkyUIftE="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.12.2"
    hash = "sha256-d8xHyML/FImuPmFOy7UGW/y85NPLzJYL6IFhR3s7XzE="
  [mod."github.com/prometheus/client_model"]
    version = "v0.2.0"
    hash = "sha256-LTHxYPRgoggl+v89ly2/RkyPIuJlmZRdGs6ZRtK3zkk="
  [mod."github.com/prometheus/common"]
    version = "v0.34.0"
    hash = "sha256-M+v+7DntUBmiQNzfNmG3aLLufbl0XBQOubtYoNTzJDA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.7.3"
    hash = "sha256-ik0WpnpSjMwifPYfQTfu/eb5ilNj+eLJF0d5Dftp8A8="
  [mod."github.com/rs/xid"]
    version = "v1.2.1"
    hash = "sha256-MnX6eVzv2iV/kAhRAlWhE+qjXfzXRMa4GkdwPGML/O0="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/shopspring/decimal"]
    version = "v1.2.0"
    hash = "sha256-f4Sk7p3S4ClpJN9sfm5MOJhWftcXrGgpX2ArRLt8TBg="
  [mod."github.com/shurcooL/sanitized_anchor_name"]
    version = "v1.0.0"
    hash = "sha256-DtFSzeLmD1fAl103ncgwab7Vv2F0aulsA+gbkq24ab8="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.8.1"
    hash = "sha256-vUIDlLXYBD74+JqdoSx+W3J6r5cOk63heo0ElsHizoM="
  [mod."github.com/slackhq/nebula"]
    version = "v1.5.2"
    hash = "sha256-693FsnN6q4Zty46ff2AyQUjCoj8XVsBBvTEbYIeEwLE="
  [mod."github.com/smallstep/certificates"]
    version = "v0.22.1"
    hash = "sha256-cIE3weYHNKrswA3MBt15QJ+xVoSuyFsfYo/F8cy4sjs="
  [mod."github.com/smallstep/cli"]
    version = "v0.22.1"
    hash = "sha256-sHIrrgaO3OT+qEJzk6VtvW8B/kaM7PjJk2ufoqREEp8="
  [mod."github.com/smallstep/nosql"]
    version = "v0.4.0"
    hash = "sha256-C3CqfEpMQbddxBf3d3Px+XQrZ5nSvwYkmaJdAKcg/Dk="
  [mod."github.com/smallstep/truststore"]
    version = "v0.12.0"
    hash = "sha256-16ZfeZonSNZVH7BL6KtJKedn20DSid/y7J7fWqNTge8="
  [mod."github.com/spf13/cast"]
    version = "v1.4.1"
    hash = "sha256-jaY+/RKUviKnE2h8Ly5cdZYinSE0uc32FW6+xfZ1Ghs="
  [mod."github.com/spf13/cobra"]
    version = "v1.5.0"
    hash = "sha256-rcyHWrxshA5DVpxrSba5X4NjppqOGrJ64QkUKKnfW2E="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/stoewer/go-strcase"]
    version = "v1.2.0"
    hash = "sha256-Vc8Ecx5DBeAK89TgqxaHV7TUrpjGMUdV6cOc3FM297A="
  [mod."github.com/tailscale/tscert"]
    version = "v0.0.0-20220316030059-54bbcb9f74e2"
    hash = "sha256-5GVkH/I9GNmYhc3H88M0Nri4HuHQ0hWJef5BT5CiW74="
  [mod."github.com/urfave/cli"]
    version = "v1.22.5"
    hash = "sha256-EhQgL2uWt4JmeCpcyKZ/FnMnkEQyCIMBviZy/BJ4TPg="
  [mod."github.com/yuin/goldmark"]
    version = "v1.5.2"
    hash = "sha256-IR19krj7bhVPsaIJrj6os5lT8/j/MilI5rqUSMGO+iU="
  [mod."github.com/yuin/goldmark-highlighting"]
    version = "v0.0.0-20220208100518-594be1970594"
    hash = "sha256-1qjdNykoWAkQjZsKZMG1l9+n0ySpzUiSiVVXKn4vx28="
  [mod."gitlab.com/NebulousLabs/fastrand"]
    version = "v0.0.0-20181126182046-603482d69e40"
    hash = "sha256-ANkqamSQYAoDO03ua//PRdleh6l3m9pJeyH8rRuLuPo="
  [mod."gitlab.com/NebulousLabs/go-upnp"]
    version = "v0.0.0-20211002182029-11da932010b6"
    hash = "sha256-waDV9T6LJqSiTdV50Omm1bk/Dhcd0hwCmFHxYgY1tqs="
  [mod."go.etcd.io/bbolt"]
    version = "v1.3.6"
    hash = "sha256-DenVAmyN22xUiivk6fdJp4C9ZnUJXCMDUf8E0goRRV4="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.11.1"
    hash = "sha256-9MxPT9X9bH1NP+KKqGr3yfqCV7ud3rRqNMHHyL5E4Qg="
  [mod."go.mozilla.org/pkcs7"]
    version = "v0.0.0-20210826202110-33d05740a352"
    hash = "sha256-x5OuHrnMWNfcLZCyQ6zaGm+ah8DMli2CCQg5z6qWgb8="
  [mod."go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"]
    version = "v0.34.0"
    hash = "sha256-/ZyRX5qjNUhvGO9X1UCG87dws28BwB+839ixVfdKAyA="
  [mod."go.opentelemetry.io/otel"]
    version = "v1.9.0"
    hash = "sha256-rP9kSnsGDaUDiYrQkBchHPLHGBJv5D16lR+UJ4wIzw8="
  [mod."go.opentelemetry.io/otel/exporters/otlp/internal/retry"]
    version = "v1.4.0"
    hash = "sha256-w2Mijx+TrOtmvXRXhqD11HUy4UAQjFczA5DbTtnIjRI="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace"]
    version = "v1.4.0"
    hash = "sha256-5Dgje2N72xfXuVq37mTxYHBoqJ6hElQtWMhcdgOMLfA="
  [mod."go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"]
    version = "v1.4.0"
    hash = "sha256-foDkdUPzhDbII2tusO2hzN7eKoaoz6oam+4d/CUh8/Q="
  [mod."go.opentelemetry.io/otel/metric"]
    version = "v0.31.0"
    hash = "sha256-r8PJRiP8SwNRguhoDVaK/uSkXQhplMtKZoGfEQJoa4k="
  [mod."go.opentelemetry.io/otel/sdk"]
    version = "v1.4.0"
    hash = "sha256-/ytwnbIcTA4KP50aVuFm2F2wK+AD7XPysxx5HZpHAJI="
  [mod."go.opentelemetry.io/otel/trace"]
    version = "v1.9.0"
    hash = "sha256-zHQ67CcTsSVukBH3MKIycJKeWYXSnEgql/Jxq8ixjLI="
  [mod."go.opentelemetry.io/proto/otlp"]
    version = "v0.12.0"
    hash = "sha256-2faHqCARouQft8l8xuHmJW+NWuB8vz9Pl8HR9J7q4WI="
  [mod."go.step.sm/cli-utils"]
    version = "v0.7.4"
    hash = "sha256-8XDOY62t7wOU4VVLcV1Fh+A2l45/2VhIXYwHfT7uzbY="
  [mod."go.step.sm/crypto"]
    version = "v0.18.0"
    hash = "sha256-Ljo6Afgl4y13eyEcdyYc7PmYdPiF5cDI/r96z09LFFU="
  [mod."go.step.sm/linkedca"]
    version = "v0.18.0"
    hash = "sha256-vkmM6w4NnAsTOAl0DsWgHvntay0O3cKD/UkmttAULLk="
  [mod."go.uber.org/atomic"]
    version = "v1.9.0"
    hash = "sha256-D8OtLaViqPShz1w8ijhIHmjw9xVaRu0qD2hXKj63r4Q="
  [mod."go.uber.org/multierr"]
    version = "v1.8.0"
    hash = "sha256-WHWgw6hLI4tPKEqJt+WC38yt64OGCXfkUJDem6mM+Mw="
  [mod."go.uber.org/zap"]
    version = "v1.23.0"
    hash = "sha256-A/Wf2F9yc+OTyX86QjTtzemUOaFSd7ptoNFaqr2smig="
  [mod."golang.org/x/crypto"]
    version = "v0.0.0-20221005025214-4161e89ecf1b"
    hash = "sha256-oU/a2iYUHp/bV1weLjkrjrfutQ5poN6PYHZIdHOm6cI="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20220722155223-a9213eeb770e"
    hash = "sha256-kNgzydWRpjm0sZl4uXEs3LX5L0xjJtJRAFf/CTlYUN4="
  [mod."golang.org/x/mod"]
    version = "v0.6.0-dev.0.20220419223038-86c51ed26bb4"
    hash = "sha256-HS5GtzK6mLkQ/FM+GWoX4wSW0XllHK/2O3Y7O2/sFBk="
  [mod."golang.org/x/net"]
    version = "v0.7.0"
    hash = "sha256-LgZYZRwtMqm+soNh+esxDSeRuIDxRGb9OEfYaFJHCDI="
  [mod."golang.org/x/sys"]
    version = "v0.5.0"
    hash = "sha256-0LTr3KeJ1OMQAwYUQo1513dXJtQAJn5Dq8sFkc8ps1U="
  [mod."golang.org/x/term"]
    version = "v0.5.0"
    hash = "sha256-f3DiX7NkDsEZpPS+PbmnOH9F5WHFZ1sQrfFg/T2UPno="
  [mod."golang.org/x/text"]
    version = "v0.7.0"
    hash = "sha256-ydgUqX+t5Qke16C6d3FP/06U/N1n+rUKpLRFj4KXjwk="
  [mod."golang.org/x/tools"]
    version = "v0.1.12"
    hash = "sha256-D0kGneGMt+LFbdUDo9Axd0yB0a5t3Z0YKVAnJDDaBo8="
  [mod."google.golang.org/genproto"]
    version = "v0.0.0-20230110181048-76db0878b65f"
    hash = "sha256-Jc90F9KU+ZKI0ynF/p3Vwl7TJPb7/MxDFs0ebagty2s="
  [mod."google.golang.org/grpc"]
    version = "v1.53.0"
    hash = "sha256-LkB13k1JaQ7e4nGpCoEA9q4T8oIV0KvkFIDZmHhDr08="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
  [mod."gopkg.in/natefinch/lumberjack.v2"]
    version = "v2.0.0"
    hash = "sha256-CLir3wRkgNy7tXQWODk7u3RP/W7qIsO2LADdM6/vWtQ="
  [mod."gopkg.in/square/go-jose.v2"]
    version = "v2.6.0"
    hash = "sha256-GRzbqF2tkyZ8/XEDkGNxF7TxBxd3z3umy/zD6jqGNqw="
  [mod."gopkg.in/tomb.v1"]
    version = "v1.0.0-20141024135613-dd632973f1e7"
    hash = "sha256-W/4wBAvuaBFHhowB67SZZfXCRDp5tzbYG4vo81TAFdM="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."howett.net/plist"]
    version = "v1.0.0"
    hash = "sha256-sySpZjk+EXYSv4cqtRiyVWOQ68W/SlrE/uyI4o/5CGY="
